<a href="https://colab.research.google.com/github/Pema-Codes/pytorch-learning/blob/main/01_pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch
import numpy as np

#Initializing a Tensor (Creation)

I will show you different ways to summon a Tensor into existence.

##1. Directly from raw data or numpy array

In [18]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [19]:
#Tensors can be created from NumPy arrays.
np_arrays = np.array(data)
x_np = torch.from_numpy(np_arrays)

##2. From Another Tensors: Copycat Tensors (_like)

In [20]:
#copies its shape (e.g., 2x2) and data type, but fills it entirely with 1s.
#retains the properties of x_data
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [21]:
#torch.rand_like does the same but fills it with random numbers.
#overrides the datatype of x_data

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.5857, 0.0059],
        [0.6143, 0.3355]]) 



##3. Brand New Tensors from Scratch

You pass a shape tuple (like (2,3), meaning 2 rows and 3 columns) to torch.rand(), torch.ones(), or torch.zeros().


In [22]:
#shape is a tuple of tensor dimensions.
shape = (3,3)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zero_tensor} \n")


Random Tensor: 
 tensor([[0.0738, 0.4781, 0.8660],
        [0.2251, 0.2021, 0.9585],
        [0.8858, 0.5166, 0.0201]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 



#2. Atrributes & Operations (Reading & Moving)

Once you have a tensor, you need to know what it is, where it lives, and how to change its position.

##Tensor Attributes

Every Tensor has three basic identity markers:
1. Shape: How big is it? (e.g., torch.Size([3, 4]) means 3 rows, 4 columns).

2. Datatype (dtype): What kind of numbers are inside? (e.g., float32 means decimals).

3. Device: Where does it physically live? (cpu or an accelerator like cuda/mps).

In [23]:
tensor = torch.rand(4,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Data type of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([4, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu


## Moving to Accelerators

Tensors start on your CPU by default. You use tensor.to('cuda') (or torch.accelerator.current_accelerator()) to copy the data onto your GPU for fast processing (Use of .to method).

Copying large tensors across devices can be expensive in terms of time and memory!

In [24]:
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator())

# Arithmetic & Operations

This is where you make tensors actually do things.

##Slicing and Indexing

In [25]:
tensor = torch.ones(4,4) #creates a tensor

#Access specific rows and columns using indexing
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

#Modify parts of the tensor
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


##Joining Tensors (Concatenation) torch.cat

You can use torch.cat to concatenate a sequence of tensors along a given dimension.

In [26]:
#join them horizontally (dim=1), vertically (dim=0)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## Matrix Multiplication (@ or .matmul) vs. Element-wise (* or .mul)

`.matmul` is the method equivalent to the `@` operator.

In [27]:
#Matrix multiplication
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1) #acts as a temporary placeholder
torch.matmul(tensor, tensor.T, out=y3)  #PyTorch overwrites the random numbers inside y3 with the final answer

#Element-wise multiplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Matrix multiplication:
@ or .matmul() performs matrix multiplication. Requires compatible dimensions for matrix algebra.

Instead of creating brand new Tensor in your computer's RAM to store the result, PyTorch overwrites the random numbers inside y3 with the final answer. This can save memory and computation time, especially with very large tensors or in loops.

Element-wise multiplication (also known as Hadamard product) * or .mul() multiplies corresponding elements of two tensors.
For this operation, the tensors must have compatible shapes for element-by-element operation.
Both lines create a brand-new tensor in your RAM to hold the result (z1 and z2).

##Extracting a single value (.item())

The line calculates the sum of all elements within the tensor and stores the result in a new tensor called `agg`.

 .item() method extracts that single numerical value from the tensor and returns it as a standard Python number (e.g., a float or an int).

In [16]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


## In-place Operations

In-place operations modify the tensor's memory directly without creating a new copy. While it saves RAM, it wipes out the history of the tensor, which breaks PyTorch's Autograd (automatic differentiation).

In [28]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## Converting to NumPy Array

In [29]:
# To convert a tensor on the CPU to a NumPy array:
numpy_array = tensor.numpy()
print(f"NumPy array: {numpy_array}")
print(f"Type of NumPy array: {type(numpy_array)}")

# Modifying the NumPy array will also modify the original tensor on the CPU
numpy_array[0, 0] = 99
print(f"\nModified NumPy array: {numpy_array}")
print(f"Original tensor after NumPy modification: {tensor}")

NumPy array: [[6. 5. 6. 6.]
 [6. 5. 6. 6.]
 [6. 5. 6. 6.]
 [6. 5. 6. 6.]]
Type of NumPy array: <class 'numpy.ndarray'>

Modified NumPy array: [[99.  5.  6.  6.]
 [ 6.  5.  6.  6.]
 [ 6.  5.  6.  6.]
 [ 6.  5.  6.  6.]]
Original tensor after NumPy modification: tensor([[99.,  5.,  6.,  6.],
        [ 6.,  5.,  6.,  6.],
        [ 6.,  5.,  6.,  6.],
        [ 6.,  5.,  6.,  6.]])
